"""phase6_learning

Revision ID: 7ae2a4590a37
Revises: f3fd90fbb1c1
Create Date: 2026-05-21 16:02:52.942788

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7ae2a4590a37'
down_revision: str | None = 'f3fd90fbb1c1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_sessions', sa.Integer(), nullable=False),
    sa.Column('completed_sessions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_items_next_review_at'), 'learning_items', ['next_review_at'], unique=False)
    op.create_index(op.f('ix_learning_items_owner_id'), 'learning_items', ['owner_id'], unique=False)
    op.create_index(op.f('ix_learning_items_status'), 'learning_items', ['status'], unique=False)
    op.create_index(op.f('ix_learning_items_topic'), 'learning_items', ['topic'], unique=False)
    op.create_table('learning_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('learning_item_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['learning_item_id'], ['learning_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_sessions_learning_item_id'), 'learning_sessions', ['learning_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_sessions_learning_item_id'), table_name='learning_sessions')
    op.drop_table('learning_sessions')
    op.drop_index(op.f('ix_learning_items_topic'), table_name='learning_items')
    op.drop_index(op.f('ix_learning_items_status'), table_name='learning_items')
    op.drop_index(op.f('ix_learning_items_owner_id'), table_name='learning_items')
    op.drop_index(op.f('ix_learning_items_next_review_at'), table_name='learning_items')
    op.drop_table('learning_items')
    # ### end Alembic commands ###
