"""phase5_user_telegram

Revision ID: f3fd90fbb1c1
Revises: 701605e22343
Create Date: 2026-05-21 15:53:54.167569

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f3fd90fbb1c1'
down_revision: str | None = '701605e22343'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_chat_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'telegram_chat_id')
    op.alter_column('tasks', 'snoozed_until',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('tasks', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('tasks', 'scheduled_end',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('tasks', 'scheduled_start',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('tasks', 'due_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('note_sources', 'last_synced_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_note_documents_source_id'), table_name='note_documents')
    op.drop_index(op.f('ix_note_documents_owner_id'), table_name='note_documents')
    op.drop_index(op.f('ix_note_documents_checksum'), table_name='note_documents')
    op.create_index(op.f('ix_note_docs_source_id'), 'note_documents', ['source_id'], unique=False)
    op.create_index(op.f('ix_note_docs_owner_id'), 'note_documents', ['owner_id'], unique=False)
    op.create_index(op.f('ix_note_docs_checksum'), 'note_documents', ['checksum'], unique=False)
    op.alter_column('note_documents', 'indexed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_extracted_entities_status'), table_name='extracted_entities')
    op.drop_index(op.f('ix_extracted_entities_owner_id'), table_name='extracted_entities')
    op.create_index(op.f('ix_entities_status'), 'extracted_entities', ['status'], unique=False)
    op.create_index(op.f('ix_entities_owner_id'), 'extracted_entities', ['owner_id'], unique=False)
    # ### end Alembic commands ###
